### ISSUE TITLE
Status packet ignored on writing data

### ISSUE THREAD

**Issue by peter-moran** [vanadiumlabs/arbotix#10]
In `arbotix/libraries/Bioloid/ax12.cpp` under `ax12SetRegister()` and `ax12SetRegister2()`, why is `ax12ReadPacket()` commented out?

I have found that on quick calls of `ax12GetRegister()` and `ax12SetRegister()`, `ax12GetRegister()` will return errors at a high rate (from returning -1 to returning the value for the other motor). However, when I uncommented `//ax12ReadPacket();` and replaced it with `ax12ReadPacket(6);`, reading a register no longer returned errors, and overall performance seemed to improve.

Is there a reason this was commented out?

**Comment by peter-moran** [comment]
Pull request #11 fixes this issue and can be merged without conflict.

**Comment by mikeferguson** [comment]
Archiving shortly
