### ISSUE TITLE
Upgrade to support latest Arduino IDE

### ISSUE THREAD

**Issue by Da5hes** [vanadiumlabs/arbotix#13]
the Arduino ecosystem has progressed a lot since Arduino IDE 1.0.6 introducing breaking changes along the way,
currently the 1.06 version is not compatible with OS X Big Sur 11.6 and thus the arbotix sketchbooks and libraries are not in a usable state on those systems as well

a migration guide is available by Arduino in this [Wiki page](https://github.com/arduino/Arduino/wiki/Arduino-Hardware-Cores-migration-guide-from-1.0-to-1.6)

**Comment by mikeferguson** [comment]
Vanadium Labs folded almost a decade ago, the folks over at Trossen have been maintaining their own fork here: https://github.com/Interbotix/arbotix - perhaps that is up to date?

**Comment by Da5hes** [comment]
@mikeferguson thanks for pointing that out,
i have tried the interbotix version and it worked fine until i tried to assign ID's to my servos with dynamixel wizard
now my Arbotix-M is not responding to any upload nor to the reset button on it, i guess that's the bootloader that got corrupted somehow, but i am lost in terms of how to fix it now.

is the right way to reflash the bootloader would be to use an ISP now that the serial is not responding?

any guidance is much appreciated
