### ISSUE TITLE
Investigate dropping custom core

### ISSUE THREAD

**Issue by mikeferguson** [vanadiumlabs/arbotix#6]
There are reports that the newest core has fast-enough serial.

**Comment by KurtE** [comment]
Yes you might try out the 1.5.6 release.  I have had some pretty good luck with it.  More details up on the thread: http://forums.trossenrobotics.com/showthread.php?5786-Arbotix-on-Arduino-1-5%28will-be-1-0-2%29-IDE/page2&highlight=Phantom+Phoenix+serial

**Comment by mikeferguson** [comment]
Archiving shortly
